# Environment variables
env:
  JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
  VERSION: $(mvn git-commit-id:revision help:evaluate -Dexpression=project.version | grep -E '^[0-9.]+')

steps:
  - label: "IRI"
    commands:
      - "make check"
      - "git clone https://github.com/iotaledger/iri-regression-tests.git"
      - "echo ${VERSION} > tmp"
      - "cd iri-regression-tests"
      - "mkdir iri"
      - "cp -rf ../target iri/target"
      - "bash -x run_all_stable_tests.sh $(cat ../tmp)"
